### ISSUE TITLE
Initial TODO list

### ISSUE THREAD

**Issue by monkeyman192** [monkeyman192/MBINCompiler-test-data#1]
- [x] Add a data folder
 - [x] Add a script which zips up only the data folder (or add as step in CI stages)
 - [x] Add some CI support (Circle CI)
CI Pipeline:
 - [x] Run script to zip up data
 - [x] Upload zip as a release with name as the current version (version == steam build ID)
